[tool.poetry]
name = "project-10-1-practice"
version = "0.1.0"
description = ""
authors = ["Kalyuzhnyy Dmitry <difrom_pro@mail.ru>"]
readme = "README.md"
packages = [{include = "project_10"}]

[tool.poetry.dependencies]
python = "^3.14"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
